#!/bin/zsh


# source alias files
source "$HOME/.aliases"

# nvm
source "$HOME/.nvm/nvm.sh" 

# go
export PATH=$PATH:/usr/local/go/bin

# this should go at end (or pretty close)
eval "$(starship init zsh)"
